Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repositoryRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $repositoryRoot 'scripts/NuGetAdmittedReleaseIdentity.ps1')
. (Join-Path $repositoryRoot 'scripts/NuGetRecoveryReleaseEvidenceClaims.ps1')
function Assert-Eq($E,$A,[string]$M){if($E-cne$A){throw "$M Expected '$E', actual '$A'."}}
function Assert-True([bool]$V,[string]$M){if(-not$V){throw $M}}
function Assert-Throws([scriptblock]$B,[string]$C){try{&$B;throw 'Expected exception was not thrown.'}catch{if($_.Exception.Message-eq'Expected exception was not thrown.'){throw};if($_.Exception.Message-notlike"*$C*"){throw "Unexpected exception: $($_.Exception.Message)"}}}
function Invoke-Case([string]$I,[string]$N,[scriptblock]$B){try{&$B;[pscustomobject]@{Id=$I;Name=$N;Outcome='PASS'}}catch{[pscustomobject]@{Id=$I;Name=$N;Outcome='FAIL';Error=$_.Exception.Message}}}
function New-Release {$s=[pscustomobject]@{ProductionKind='Release';SourceCommit=('b'*40);PackageVersion='1.0.4';ReleaseAuthorityTag='v1.0.4';Packages=@([pscustomobject]@{Id='A';Version='1.0.4';Sha256=('a'*64)},[pscustomobject]@{Id='B';Version='1.0.4';Sha256=('b'*64)},[pscustomobject]@{Id='C';Version='1.0.4';Sha256=('c'*64)})};$i=Get-NuGetAdmittedReleaseIdentity $s;$p=$i.Projection;$p|Add-Member Sha256 $i.Sha256;return $p}
function New-OriginalLedger([object]$R){[pscustomobject]@{operationId='00000000-0000-0000-0000-000000000301';ledgerState='Terminal';registry='NuGet.org';sourceCommit=$R.SourceCommit;packageVersion=$R.PackageVersion;releaseAuthorityTag=$R.ReleaseAuthorityTag;startedAtUtc='2026-09-24T00:00:00Z';completedAtUtc='2026-09-24T00:01:00Z';operationConclusion='StoppedRejected';packages=@([pscustomobject]@{id='A';version='1.0.4';admittedSha256=('a'*64);mutationState='Accepted';statusCode=201;diagnostic=$null},[pscustomobject]@{id='B';version='1.0.4';admittedSha256=('b'*64);mutationState='Rejected';statusCode=409;diagnostic=[pscustomobject]@{Code='ExistingIdentityConflict'}},[pscustomobject]@{id='C';version='1.0.4';admittedSha256=('c'*64);mutationState='NotAttempted';statusCode=$null;diagnostic=$null})}}
function New-ContinuationLedger([object]$R){[pscustomobject]@{operationId='00000000-0000-0000-0000-000000000302';operationKind='Continuation';historicalPublicationOperationId='00000000-0000-0000-0000-000000000301';packageIndex=2;ledgerState='Terminal';registry='NuGet.org';sourceCommit=$R.SourceCommit;packageVersion=$R.PackageVersion;releaseAuthorityTag=$R.ReleaseAuthorityTag;startedAtUtc='2026-09-24T01:00:00Z';completedAtUtc='2026-09-24T01:01:00Z';operationConclusion='Indeterminate';packages=@([pscustomobject]@{id='C';version='1.0.4';admittedSha256=('c'*64);mutationState='Indeterminate';statusCode=$null;diagnostic=[pscustomobject]@{Code='TransportUncertainty'}})}}
function New-Recovery([object]$L,[int]$PackageOffset,[string]$Trigger,[string]$State){$p=@($L.packages)[$PackageOffset];[pscustomobject]@{HistoricalPublication=[pscustomobject]@{Operation=[pscustomobject]@{OperationId=$L.operationId;LedgerState=$L.ledgerState;OperationConclusion=$L.operationConclusion;StartedAtUtc=$L.startedAtUtc;CompletedAtUtc=$L.completedAtUtc;Registry=$L.registry};Package=[pscustomobject]@{Id=$p.id;Version=$p.version;AdmittedSha256=$p.admittedSha256;MutationState=$p.mutationState;StatusCode=$p.statusCode;Diagnostic=$p.diagnostic}};Recovery=[pscustomobject]@{Trigger=$Trigger;RecoveryState=$State}}}
$results=@()
$results+=Invoke-Case C301 'original recovery inherits canonical position from source ledger' {$r=New-Release;$l=New-OriginalLedger $r;$c=ConvertFrom-NuGetRecoveryEvidenceClaim (New-Recovery $l 1 Conflict409 Converged) $l $r;Assert-Eq '1' ([string]$c.PackageIndex) 'index';Assert-Eq OriginalRecovery $c.EvidenceSource 'source'}
$results+=Invoke-Case C302 'continuation recovery inherits explicit continuation position' {$r=New-Release;$l=New-ContinuationLedger $r;$c=ConvertFrom-NuGetRecoveryEvidenceClaim (New-Recovery $l 0 IndeterminateMutation Converged) $l $r;Assert-Eq '2' ([string]$c.PackageIndex) 'index';Assert-Eq ContinuationRecovery $c.EvidenceSource 'source'}
$results+=Invoke-Case C303 'recovery preserves exact R N package identity' {$r=New-Release;$l=New-OriginalLedger $r;$c=ConvertFrom-NuGetRecoveryEvidenceClaim (New-Recovery $l 1 Conflict409 Conflict) $l $r;Assert-Eq $r.Sha256 $c.ReleaseIdentitySha256 'R';Assert-Eq B $c.PackageId 'id';Assert-Eq ('b'*64) $c.AdmittedSha256 'sha'}
$results+=Invoke-Case C304 'operation identity must match source ledger' {$r=New-Release;$l=New-OriginalLedger $r;$e=New-Recovery $l 1 Conflict409 Converged;$e.HistoricalPublication.Operation.OperationId='other';Assert-Throws {ConvertFrom-NuGetRecoveryEvidenceClaim $e $l $r} 'uniquely join'}
$results+=Invoke-Case C305 'package identity must match source ledger' {$r=New-Release;$l=New-OriginalLedger $r;$e=New-Recovery $l 1 Conflict409 Converged;$e.HistoricalPublication.Package.Id='C';Assert-Throws {ConvertFrom-NuGetRecoveryEvidenceClaim $e $l $r} 'uniquely join'}
$results+=Invoke-Case C306 'historical mutation state must match source lifecycle' {$r=New-Release;$l=New-OriginalLedger $r;$e=New-Recovery $l 1 Conflict409 Converged;$e.HistoricalPublication.Package.MutationState='Attempting';Assert-Throws {ConvertFrom-NuGetRecoveryEvidenceClaim $e $l $r} 'mutation lifecycle'}
$results+=Invoke-Case C307 'historical operation lifecycle must match source ledger' {$r=New-Release;$l=New-OriginalLedger $r;$e=New-Recovery $l 1 Conflict409 Converged;$e.HistoricalPublication.Operation.LedgerState='InProgress';Assert-Throws {ConvertFrom-NuGetRecoveryEvidenceClaim $e $l $r} 'operation lifecycle'}
$results+=Invoke-Case C308 'recovery trigger must correspond to source mutation' {$r=New-Release;$l=New-OriginalLedger $r;$e=New-Recovery $l 1 IndeterminateMutation Converged;Assert-Throws {ConvertFrom-NuGetRecoveryEvidenceClaim $e $l $r} 'trigger does not match'}
$results+=Invoke-Case C309 'terminal recovery states remain raw evidence' {$r=New-Release;$l=New-OriginalLedger $r;foreach($s in @('Converged','Conflict','Unresolved')){$c=ConvertFrom-NuGetRecoveryEvidenceClaim (New-Recovery $l 1 Conflict409 $s) $l $r;Assert-Eq $s $c.RecoveryState 'state';Assert-True ($null-eq$c.PSObject.Properties['EffectiveState']) 'D2 reduction occurred'}}
$results+=Invoke-Case C310 'nonterminal recovery state is rejected' {$r=New-Release;$l=New-OriginalLedger $r;Assert-Throws {ConvertFrom-NuGetRecoveryEvidenceClaim (New-Recovery $l 1 Conflict409 Uncertain) $l $r} 'terminal Converged, Conflict, or Unresolved'}
$results+=Invoke-Case C311 'join does not use timestamps for position authority' {$r=New-Release;$l=New-OriginalLedger $r;$e=New-Recovery $l 1 Conflict409 Converged;$e.Recovery|Add-Member StartedAtUtc '1900-01-01T00:00:00Z';$c=ConvertFrom-NuGetRecoveryEvidenceClaim $e $l $r;Assert-Eq '1' ([string]$c.PackageIndex) 'index'}
$results+=Invoke-Case C312 'continuation historical pointer is preserved but not traversed' {$r=New-Release;$l=New-ContinuationLedger $r;$l.historicalPublicationOperationId='does-not-exist';$c=ConvertFrom-NuGetRecoveryEvidenceClaim (New-Recovery $l 0 IndeterminateMutation Converged) $l $r;Assert-Eq 'does-not-exist' $c.HistoricalPublicationOperationId 'pointer';Assert-Eq '2' ([string]$c.PackageIndex) 'index'}
$results+=Invoke-Case C313 'recovery claim has no mutation authority' {$r=New-Release;$l=New-OriginalLedger $r;$c=ConvertFrom-NuGetRecoveryEvidenceClaim (New-Recovery $l 1 Conflict409 Converged) $l $r;foreach($n in @('Credential','Publish','Put','ContinuationGrant')){Assert-True ($null-eq$c.PSObject.Properties[$n]) "$n surfaced"}}
$results|Format-Table -AutoSize
$failed=@($results|Where-Object Outcome -eq FAIL);if($failed.Count){$failed|ForEach-Object{Write-Host "$($_.Id) $($_.Name): $($_.Error)" -ForegroundColor Red};throw "RP-5C.3 recovery evidence join conformance failed: $($failed.Count) case(s)."};Write-Host "RP-5C.3 recovery evidence join conformance passed: $($results.Count)/$($results.Count)."
