Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repositoryRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $repositoryRoot 'scripts/NuGetWholeReleaseEffectiveState.ps1')
function Assert-Eq($Expected,$Actual,[string]$Message){if([string]$Expected-cne[string]$Actual){throw "$Message Expected '$Expected', actual '$Actual'."}}
function Assert-Throws([scriptblock]$Body,[string]$Contains){try{&$Body;throw 'Expected exception was not thrown.'}catch{if($_.Exception.Message-eq'Expected exception was not thrown.'){throw};if($_.Exception.Message-notlike"*$Contains*"){throw "Unexpected exception: $($_.Exception.Message)"}}}
function Invoke-Case([string]$Id,[string]$Name,[scriptblock]$Body){try{&$Body;[pscustomobject]@{Id=$Id;Name=$Name;Outcome='PASS'}}catch{[pscustomobject]@{Id=$Id;Name=$Name;Outcome='FAIL';Error=$_.Exception.Message}}}
$releaseSha='f'*64
$release=[pscustomobject]@{Profile='1';Sha256=$releaseSha;SourceCommit='0123456789abcdef0123456789abcdef01234567';ReleaseAuthorityTag='v1.0.4';PackageCount=4;Packages=@(
 [pscustomobject]@{Id='A';Version='1.0.4';Sha256='a'*64},[pscustomobject]@{Id='B';Version='1.0.4';Sha256='b'*64},[pscustomobject]@{Id='C';Version='1.0.4';Sha256='c'*64},[pscustomobject]@{Id='D';Version='1.0.4';Sha256='d'*64})}
function New-State([int]$Index,[string]$State){$p=$release.Packages[$Index];[pscustomobject]@{EffectiveState=$State;ReleaseIdentityProfile='1';ReleaseIdentitySha256=$releaseSha;PackageIndex=$Index;PackageId=$p.Id;PackageVersion=$p.Version;AdmittedSha256=$p.Sha256}}
function Project([string[]]$Shape){$s=@();for($i=0;$i-lt$Shape.Count;$i++){$s+=New-State $i $Shape[$i]};Get-NuGetWholeReleaseEffectiveState -Release ([pscustomobject]@{Profile=$release.Profile;Sha256=$release.Sha256;SourceCommit=$release.SourceCommit;ReleaseAuthorityTag=$release.ReleaseAuthorityTag;PackageCount=$Shape.Count;Packages=@($release.Packages[0..($Shape.Count-1)])}) -PositionStates $s}
$results=@()
$results+=Invoke-Case 'D01' 'all satisfied is ReleaseComplete' {Assert-Eq 'ReleaseComplete' (Project @('Satisfied','Satisfied','Satisfied')).ReleaseState 'state'}
$results+=Invoke-Case 'D02' 'first unsatisfied selects exactly one continuation' {$o=Project @('Satisfied','Satisfied','Unsatisfied','Unsatisfied');Assert-Eq 'ContinuationEligible' $o.ReleaseState 'state';Assert-Eq 2 $o.PackageIndex 'index';Assert-Eq 'C' $o.PackageId 'id'}
$results+=Invoke-Case 'D03' 'first indeterminate is release Indeterminate' {Assert-Eq 'Indeterminate' (Project @('Satisfied','Indeterminate','Unsatisfied')).ReleaseState 'state'}
$results+=Invoke-Case 'D04' 'any blocked position blocks release' {Assert-Eq 'Blocked' (Project @('Satisfied','Blocked','Unsatisfied')).ReleaseState 'state'}
$results+=Invoke-Case 'D05' 'satisfaction beyond gap is structural Blocked' {$o=Project @('Satisfied','Unsatisfied','Satisfied');Assert-Eq 'Blocked' $o.ReleaseState 'state';Assert-Eq 'OutOfSequenceSatisfaction' $o.Reason 'reason'}
$results+=Invoke-Case 'D06' 'indeterminate beyond gap is release Indeterminate' {$o=Project @('Satisfied','Unsatisfied','Indeterminate');Assert-Eq 'Indeterminate' $o.ReleaseState 'state';Assert-Eq 'EvidenceBeyondContinuationBoundary' $o.Reason 'reason'}
$results+=Invoke-Case 'D07' 'blocked beyond gap dominates' {$o=Project @('Satisfied','Unsatisfied','Blocked');Assert-Eq 'Blocked' $o.ReleaseState 'state';Assert-Eq 'BlockedPosition' $o.Reason 'reason'}
$results+=Invoke-Case 'D08' 'later satisfaction after multiple gaps blocks' {$o=Project @('Satisfied','Unsatisfied','Unsatisfied','Satisfied');Assert-Eq 'Blocked' $o.ReleaseState 'state';Assert-Eq 'OutOfSequenceSatisfaction' $o.Reason 'reason'}
$results+=Invoke-Case 'D09' 'later indeterminate after multiple gaps is indeterminate' {$o=Project @('Satisfied','Unsatisfied','Unsatisfied','Indeterminate');Assert-Eq 'Indeterminate' $o.ReleaseState 'state';Assert-Eq 'EvidenceBeyondContinuationBoundary' $o.Reason 'reason'}
$results+=Invoke-Case 'D10' 'indeterminate before later satisfaction remains Indeterminate' {$o=Project @('Satisfied','Indeterminate','Satisfied');Assert-Eq 'Indeterminate' $o.ReleaseState 'state';Assert-Eq 'IndeterminatePosition' $o.Reason 'reason'}
$results+=Invoke-Case 'D11' 'blocked dominates indeterminate anywhere' {Assert-Eq 'Blocked' (Project @('Indeterminate','Unsatisfied','Blocked')).ReleaseState 'state'}
$results+=Invoke-Case 'D12' 'unsatisfied terminal position is continuation eligible' {$o=Project @('Satisfied','Satisfied','Unsatisfied');Assert-Eq 'ContinuationEligible' $o.ReleaseState 'state';Assert-Eq 2 $o.PackageIndex 'index'}
$results+=Invoke-Case 'D13' 'continuation selection preserves exact package identity and release provenance' {$o=Project @('Satisfied','Unsatisfied','Unsatisfied');Assert-Eq $releaseSha $o.ReleaseIdentitySha256 'release';Assert-Eq 'B' $o.PackageId 'id';Assert-Eq ('b'*64) $o.AdmittedSha256 'sha';Assert-Eq $release.SourceCommit $o.SourceCommit 'commit';Assert-Eq $release.ReleaseAuthorityTag $o.ReleaseAuthorityTag 'tag'}
$results+=Invoke-Case 'D14' 'continuation result exposes no mutation authority' {$o=Project @('Satisfied','Unsatisfied','Unsatisfied');foreach($name in @('RemoteAdmission','ContinuationGrant','ContinuationOperationId','CredentialAuthority','PUTAuthority','SuffixAuthority')){if($null-ne$o.PSObject.Properties[$name]){throw "D3 leaked forbidden authority $name."}}}
$results+=Invoke-Case 'D15' 'projection requires one state per canonical position' {$states=@((New-State 0 'Satisfied'),(New-State 1 'Unsatisfied'));Assert-Throws {Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $states} 'exactly one effective position state'}
$results+=Invoke-Case 'D16' 'canonical array order is position authority' {$states=@((New-State 1 'Satisfied'),(New-State 0 'Unsatisfied'),(New-State 2 'Unsatisfied'),(New-State 3 'Unsatisfied'));Assert-Throws {Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $states} 'exact release identity and canonical position'}
$results+=Invoke-Case 'D17' 'position from another release is rejected' {$states=@((New-State 0 'Satisfied'),(New-State 1 'Unsatisfied'),(New-State 2 'Unsatisfied'),(New-State 3 'Unsatisfied'));$states[1].ReleaseIdentitySha256='e'*64;Assert-Throws {Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $states} 'exact release identity and canonical position'}
$results+=Invoke-Case 'D18' 'package mismatch is rejected' {$states=@((New-State 0 'Satisfied'),(New-State 1 'Unsatisfied'),(New-State 2 'Unsatisfied'),(New-State 3 'Unsatisfied'));$states[1].PackageId='Wrong';Assert-Throws {Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $states} 'canonical package identity'}
$results+=Invoke-Case 'D19' 'unsupported effective state is rejected' {$states=@((New-State 0 'Satisfied'),(New-State 1 'Pending'),(New-State 2 'Unsatisfied'),(New-State 3 'Unsatisfied'));Assert-Throws {Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $states} 'unsupported state'}
$results+=Invoke-Case 'D20' 'projection does not mutate effective position states' {$states=@((New-State 0 'Satisfied'),(New-State 1 'Unsatisfied'),(New-State 2 'Unsatisfied'),(New-State 3 'Unsatisfied'));$before=@($states|ForEach-Object{"$($_.EffectiveState)|$($_.PackageId)|$($_.PSObject.Properties.Count)"});$null=Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $states;$after=@($states|ForEach-Object{"$($_.EffectiveState)|$($_.PackageId)|$($_.PSObject.Properties.Count)"});Assert-Eq ($before-join';') ($after-join';') 'state mutation'}
$results+=Invoke-Case 'D21' 'descriptive extra fields do not affect projection' {$a=@((New-State 0 'Satisfied'),(New-State 1 'Unsatisfied'),(New-State 2 'Unsatisfied'),(New-State 3 'Unsatisfied'));$b=@();foreach($s in $a){$copy=$s|Select-Object *;$copy|Add-Member TimestampUtc ([datetime]::UtcNow.AddYears(-10));$b+=$copy};Assert-Eq (Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $a).ReleaseState (Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $b).ReleaseState 'descriptive evidence'}
$results+=Invoke-Case 'D22' 'projection evidence is selection evidence only' {$states=@((New-State 0 'Satisfied'),(New-State 1 'Unsatisfied'),(New-State 2 'Unsatisfied'),(New-State 3 'Unsatisfied'));$o=Get-NuGetWholeReleaseEffectiveState -Release $release -PositionStates $states;Assert-Eq 4 @($o.ProjectionEvidence).Count 'evidence count';Assert-Eq 'Unsatisfied' $o.ProjectionEvidence[1].EffectiveState 'selected evidence'}
$results|Format-Table -AutoSize
$failed=@($results|Where-Object Outcome -eq 'FAIL');if($failed.Count){$failed|ForEach-Object{Write-Host "$($_.Id) $($_.Name): $($_.Error)" -ForegroundColor Red};throw "RP-5D whole-release effective-state conformance failed: $($failed.Count) case(s)."};Write-Host "RP-5D whole-release effective-state conformance passed: $($results.Count)/$($results.Count)."
