Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repositoryRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $repositoryRoot 'scripts/NuGetContinuationOperation.ps1')
function Assert-Eq($Expected,$Actual,[string]$Message){if($Expected-cne$Actual){throw "$Message Expected '$Expected', actual '$Actual'."}}
function Assert-True([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Invoke-Case([string]$Id,[string]$Name,[scriptblock]$Body){try{&$Body;[pscustomobject]@{Id=$Id;Name=$Name;Outcome='PASS'}}catch{[pscustomobject]@{Id=$Id;Name=$Name;Outcome='FAIL';Error=$_.Exception.Message}}}
function Assert-Throws([scriptblock]$Body,[string]$Contains){try{&$Body;throw 'Expected exception was not thrown.'}catch{if($_.Exception.Message-eq'Expected exception was not thrown.'){throw};if($_.Exception.Message-notlike"*$Contains*"){throw "Unexpected exception: $($_.Exception.Message)"}}}
$registry='https://api.nuget.org/v3/index.json';$publish='https://www.nuget.org/api/v2/package';$serviceJson='{"resources":[{"@id":"https://www.nuget.org/api/v2/package","@type":"PackagePublish/2.0.0"}]}'
function New-Grant([string]$Artifact,[string]$Hash,[string]$Registry=$registry){[pscustomobject]@{HistoricalPublicationOperationId='00000000-0000-0000-0000-000000000401';ContinuationOperationId='00000000-0000-0000-0000-000000000402';TargetRegistryIdentity=$Registry;PackageIndex=3;PackageId='Pkg.D';PackageVersion='1.0.4-test.1';AdmittedSha256=$Hash;ArtifactPath=$Artifact;SourceCommit=('a'*40);ReleaseAuthorityTag='release/v1.0.4';RecoveryState='Converged';RemoteAdmissionState='Admissible';RemoteAdmissionReason='AuthoritativeAbsent'}}
function New-Fixture([int]$Status=201,[bool]$ThrowPublish=$false,[bool]$CredentialAvailable=$true,[bool]$ThrowCredential=$false){$s=[pscustomobject]@{Discovery=0;Availability=0;Acquire=0;Publish=0;Writes=[System.Collections.Generic.List[object]]::new();PublishedPath=$null};$d={param($u);$s.Discovery++;[pscustomobject]@{StatusCode=200;Content=$serviceJson}}.GetNewClosure();$ca={$s.Availability++;$CredentialAvailable}.GetNewClosure();$ac={$s.Acquire++;if($ThrowCredential){throw 'credential failed'};'secret'}.GetNewClosure();$p={param($e,$f,$k);$s.Publish++;$s.PublishedPath=$f;if($ThrowPublish){throw 'transport failed'};[pscustomobject]@{StatusCode=$Status}}.GetNewClosure();$w={param($l,$path);$copy=$l|ConvertTo-Json -Depth 8|ConvertFrom-Json;$s.Writes.Add($copy)}.GetNewClosure();[pscustomobject]@{State=$s;Discovery=$d;Available=$ca;Acquire=$ac;Publish=$p;Write=$w}}
$temp=Join-Path ([IO.Path]::GetTempPath()) ('pulsestack-rp4b-'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Path $temp -Force|Out-Null
$results=@()
try{$artifact=Join-Path $temp 'Pkg.D.nupkg';[IO.File]::WriteAllText($artifact,'package',[Text.UTF8Encoding]::new($false));$hash=(Get-FileHash $artifact -Algorithm SHA256).Hash.ToLowerInvariant();$grant=New-Grant $artifact $hash
$invoke={param($g,$f,$hook=$null)Invoke-NuGetContinuationOperation -Grant $g -EvidenceRoot $temp -CredentialAvailable $f.Available -AcquireCredential $f.Acquire -DiscoveryRequest $f.Discovery -PublishRequest $f.Publish -WriteLedger $f.Write -Clock {[DateTimeOffset]'2026-09-26T12:00:00Z'} -ServiceIndexUri $registry -AfterAttemptingPersisted $hook}
$results+=Invoke-Case 'O01' 'grant executes exactly one accepted package' {$f=New-Fixture;$r=&$invoke $grant $f;Assert-Eq '1' ([string]$f.State.Publish) 'PUT count';Assert-Eq $artifact $f.State.PublishedPath 'artifact';Assert-Eq 'Accepted' $r.Result.packages[0].mutationState 'state';Assert-Eq 'Accepted' $r.Result.operationConclusion 'conclusion';Assert-Eq '1' ([string]$r.Result.packages.Count) 'package count'}
$results+=Invoke-Case 'O02' 'Attempting is durable before credential and PUT' {$f=New-Fixture;$r=&$invoke $grant $f;Assert-True ($f.State.Writes.Count-ge 2) 'writes missing';Assert-Eq 'NotAttempted' $f.State.Writes[0].packages[0].mutationState 'initial';Assert-Eq 'Attempting' $f.State.Writes[1].packages[0].mutationState 'write ahead';Assert-Eq '1' ([string]$f.State.Acquire) 'acquire';Assert-Eq '1' ([string]$f.State.Publish) 'publish'}
$results+=Invoke-Case 'O03' 'credential unavailable creates no operation mutation' {$f=New-Fixture -CredentialAvailable $false;Assert-Throws {&$invoke $grant $f} 'credential is unavailable';Assert-Eq '0' ([string]$f.State.Writes.Count) 'writes';Assert-Eq '0' ([string]$f.State.Acquire) 'acquire';Assert-Eq '0' ([string]$f.State.Publish) 'publish'}
$results+=Invoke-Case 'O04' 'credential acquisition failure after Attempting is Indeterminate' {$f=New-Fixture -ThrowCredential $true;$r=&$invoke $grant $f;Assert-Eq 'Indeterminate' $r.Result.packages[0].mutationState 'state';Assert-Eq 'CredentialAcquisitionFailure' $r.Result.packages[0].diagnostic.Code 'diagnostic';Assert-Eq '0' ([string]$f.State.Publish) 'PUT'}
$results+=Invoke-Case 'O05' '409 is recoverable ExistingIdentityConflict' {$f=New-Fixture -Status 409;$r=&$invoke $grant $f;Assert-Eq 'Rejected' $r.Result.packages[0].mutationState 'state';Assert-Eq 'ExistingIdentityConflict' $r.Result.packages[0].diagnostic.Code 'diagnostic'}
$results+=Invoke-Case 'O06' 'transport uncertainty is Indeterminate' {$f=New-Fixture -ThrowPublish $true;$r=&$invoke $grant $f;Assert-Eq 'Indeterminate' $r.Result.packages[0].mutationState 'state';Assert-Eq 'TransportUncertainty' $r.Result.packages[0].diagnostic.Code 'diagnostic'}
$results+=Invoke-Case 'O07' 'crash seam leaves durable Attempting evidence' {$f=New-Fixture;$hook={throw 'simulated crash'};Assert-Throws {&$invoke $grant $f $hook} 'simulated crash';Assert-Eq 'Attempting' $f.State.Writes[$f.State.Writes.Count-1].packages[0].mutationState 'durable state';Assert-Eq '0' ([string]$f.State.Acquire) 'acquire';Assert-Eq '0' ([string]$f.State.Publish) 'PUT'}
$results+=Invoke-Case 'O08' 'registry mismatch fails before discovery or mutation' {$f=New-Fixture;$bad=New-Grant $artifact $hash 'https://example.test/v3/index.json';Assert-Throws {&$invoke $bad $f} 'registry does not match';Assert-Eq '0' ([string]$f.State.Discovery) 'discovery';Assert-Eq '0' ([string]$f.State.Writes.Count) 'writes'}
$results+=Invoke-Case 'O09' 'artifact mutation fails before discovery or mutation' {$f=New-Fixture;[IO.File]::WriteAllText($artifact,'changed',[Text.UTF8Encoding]::new($false));Assert-Throws {&$invoke $grant $f} 'changed before mutation';Assert-Eq '0' ([string]$f.State.Discovery) 'discovery';Assert-Eq '0' ([string]$f.State.Publish) 'PUT';[IO.File]::WriteAllText($artifact,'package',[Text.UTF8Encoding]::new($false))}
$results+=Invoke-Case 'O10' 'operation ledger carries continuation provenance' {$f=New-Fixture;$r=&$invoke $grant $f;Assert-Eq 'Continuation' $r.Result.operationKind 'kind';Assert-Eq $grant.HistoricalPublicationOperationId $r.Result.historicalPublicationOperationId 'historical';Assert-Eq '3' ([string]$r.Result.packageIndex) 'index';Assert-Eq $grant.ContinuationOperationId $r.Result.operationId 'operation id'}
$results+=Invoke-Case 'O11' 'operation performs no suffix iteration' {$f=New-Fixture;$r=&$invoke $grant $f;Assert-Eq '1' ([string]$r.Result.packages.Count) 'packages';Assert-Eq '1' ([string]$f.State.Publish) 'PUTs'}
$results+=Invoke-Case 'O12' 'existing operation evidence cannot be reopened' {$f=New-Fixture;$path=Join-Path (Join-Path (Join-Path $temp $grant.PackageVersion) 'attempts') $grant.ContinuationOperationId;New-Item -ItemType Directory -Path $path -Force|Out-Null;[IO.File]::WriteAllText((Join-Path $path 'publication-result.json'),'{}');Assert-Throws {&$invoke $grant $f} 'cannot be reopened';Assert-Eq '0' ([string]$f.State.Publish) 'PUT';Remove-Item $path -Recurse -Force}
}finally{Remove-Item -LiteralPath $temp -Recurse -Force -ErrorAction SilentlyContinue}
$results|Format-Table -AutoSize;$failed=@($results|Where-Object Outcome -eq 'FAIL');if($failed.Count){$failed|ForEach-Object{Write-Host "$($_.Id) $($_.Name): $($_.Error)" -ForegroundColor Red};throw "RP-4B continuation operation conformance failed: $($failed.Count) case(s)."};Write-Host "RP-4B continuation operation conformance passed: $($results.Count)/$($results.Count)."
