Set-StrictMode -Version Latest
$ErrorActionPreference='Stop'
$repositoryRoot=Split-Path -Parent (Split-Path -Parent $PSScriptRoot)
. (Join-Path $repositoryRoot 'scripts/NuGetAdmittedReleaseIdentity.ps1')
. (Join-Path $repositoryRoot 'scripts/NuGetReleaseEvidenceClaims.ps1')
function Assert-Eq($Expected,$Actual,[string]$Message){if($Expected-cne$Actual){throw "$Message Expected '$Expected', actual '$Actual'."}}
function Assert-True([bool]$Value,[string]$Message){if(-not$Value){throw $Message}}
function Assert-Throws([scriptblock]$Body,[string]$Contains){try{&$Body;throw 'Expected exception was not thrown.'}catch{if($_.Exception.Message-eq'Expected exception was not thrown.'){throw};if($_.Exception.Message-notlike"*$Contains*"){throw "Unexpected exception: $($_.Exception.Message)"}}}
function Invoke-Case([string]$Id,[string]$Name,[scriptblock]$Body){try{&$Body;[pscustomobject]@{Id=$Id;Name=$Name;Outcome='PASS'}}catch{[pscustomobject]@{Id=$Id;Name=$Name;Outcome='FAIL';Error=$_.Exception.Message}}}
function New-Release {$set=[pscustomobject]@{ProductionKind='Release';SourceCommit='0123456789abcdef0123456789abcdef01234567';PackageVersion='1.0.4';ReleaseAuthorityTag='v1.0.4';Packages=@([pscustomobject]@{Id='A';Version='1.0.4';Sha256=('a'*64)},[pscustomobject]@{Id='B';Version='1.0.4';Sha256=('b'*64)},[pscustomobject]@{Id='C';Version='1.0.4';Sha256=('c'*64)})};$identity=Get-NuGetAdmittedReleaseIdentity $set;$p=$identity.Projection;$p|Add-Member -NotePropertyName Sha256 -NotePropertyValue $identity.Sha256;return $p}
function New-ContinuationLedger([object]$Release){[pscustomobject]@{operationId='00000000-0000-0000-0000-000000000002';operationKind='Continuation';historicalPublicationOperationId='00000000-0000-0000-0000-000000000001';packageIndex=1;sourceCommit=$Release.SourceCommit;packageVersion=$Release.PackageVersion;releaseAuthorityTag=$Release.ReleaseAuthorityTag;packages=@([pscustomobject]@{id='B';version='1.0.4';admittedSha256=('b'*64);mutationState='Accepted';statusCode=201;diagnostic=$null})}}
function Add-Rp6Metadata([object]$Ledger,[object]$Release,[string]$SelectionSource,[AllowNull()][string]$HistoricalId){
 $Ledger|Add-Member releaseIdentityProfile $Release.Profile
 $Ledger|Add-Member releaseIdentitySha256 $Release.Sha256
 $Ledger|Add-Member selectionSource $SelectionSource
 $Ledger.historicalPublicationOperationId=$HistoricalId
 return $Ledger
}
$results=@()
$results+=Invoke-Case 'C201' 'continuation ledger emits exactly one normalized claim' {$r=New-Release;$c=@(ConvertFrom-NuGetContinuationPublicationLedgerClaim (New-ContinuationLedger $r) $r);Assert-Eq '1' ([string]$c.Count) 'claim count';Assert-Eq 'ContinuationPublication' $c[0].EvidenceSource 'source'}
$results+=Invoke-Case 'C202' 'explicit packageIndex is canonical position authority' {$r=New-Release;$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim (New-ContinuationLedger $r) $r;Assert-Eq '1' ([string]$c.PackageIndex) 'index';Assert-Eq 'B' $c.PackageId 'id'}
$results+=Invoke-Case 'C203' 'one-package invariant is required' {$r=New-Release;$l=New-ContinuationLedger $r;$l.packages+=([pscustomobject]@{id='C';version='1.0.4';admittedSha256=('c'*64);mutationState='NotAttempted'});Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'exactly one package'}
$results+=Invoke-Case 'C204' 'package must exactly match R at explicit position' {$r=New-Release;$l=New-ContinuationLedger $r;$l.packages[0].id='C';Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'canonical release position 1'}
$results+=Invoke-Case 'C205' 'out-of-range packageIndex is rejected' {$r=New-Release;$l=New-ContinuationLedger $r;$l.packageIndex=3;Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'outside the supplied release identity'}
$results+=Invoke-Case 'C206' 'continuation provenance is preserved' {$r=New-Release;$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim (New-ContinuationLedger $r) $r;Assert-Eq '00000000-0000-0000-0000-000000000002' $c.OperationId 'operation';Assert-Eq '00000000-0000-0000-0000-000000000001' $c.HistoricalPublicationOperationId 'historical operation'}
$results+=Invoke-Case 'C207' 'raw mutation state is preserved without D2 reduction' {$r=New-Release;$l=New-ContinuationLedger $r;$l.packages[0].mutationState='Indeterminate';$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r;Assert-Eq 'Indeterminate' $c.RawMutationState 'raw state';Assert-True ($null -eq $c.PSObject.Properties['EffectiveState']) 'normalizer performed D2 reduction'}
$results+=Invoke-Case 'C208' 'pre-RP-5 continuation evidence remains structurally validatable' {$r=New-Release;$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim (New-ContinuationLedger $r) $r;Assert-Eq $r.Sha256 $c.ReleaseIdentitySha256 'derived binding'}
$results+=Invoke-Case 'C209' 'future identity-bearing continuation must match R' {$r=New-Release;$l=New-ContinuationLedger $r;$l|Add-Member releaseIdentityProfile $r.Profile;$l|Add-Member releaseIdentitySha256 $r.Sha256;$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r;Assert-Eq $r.Sha256 $c.ReleaseIdentitySha256 'identity'}
$results+=Invoke-Case 'C210' 'mismatched future continuation identity is rejected' {$r=New-Release;$l=New-ContinuationLedger $r;$l|Add-Member releaseIdentityProfile $r.Profile;$l|Add-Member releaseIdentitySha256 ('d'*64);Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'release identity does not match'}
$results+=Invoke-Case 'C211' 'partial future continuation identity is rejected' {$r=New-Release;$l=New-ContinuationLedger $r;$l|Add-Member releaseIdentityProfile $r.Profile;Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'incomplete release identity'}
$results+=Invoke-Case 'C212' 'continuation adapter does not follow historical operation pointer' {$r=New-Release;$l=New-ContinuationLedger $r;$l.historicalPublicationOperationId='does-not-exist';$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r;Assert-Eq 'does-not-exist' $c.HistoricalPublicationOperationId 'historical pointer';Assert-Eq 'Accepted' $c.RawMutationState 'raw state'}
$results+=Invoke-Case 'C213' 'operationKind must identify continuation evidence' {$r=New-Release;$l=New-ContinuationLedger $r;$l.operationKind='Fresh';Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} "operationKind must be exactly 'Continuation'"}
$results+=Invoke-Case 'C214' 'legacy continuation without historical provenance is rejected' {$r=New-Release;$l=New-ContinuationLedger $r;$l.historicalPublicationOperationId=$null;Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'Legacy continuation ledger historical publication operation provenance is required'}
$results+=Invoke-Case 'C215' 'RP-6 RP-3 continuation accepts identity source and historical provenance' {$r=New-Release;$l=Add-Rp6Metadata (New-ContinuationLedger $r) $r 'RP3RecoveryContinuation' '00000000-0000-0000-0000-000000000001';$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r;Assert-Eq '00000000-0000-0000-0000-000000000001' $c.HistoricalPublicationOperationId 'historical'}
$results+=Invoke-Case 'C216' 'RP-6 RP-3 continuation without historical provenance is rejected' {$r=New-Release;$l=Add-Rp6Metadata (New-ContinuationLedger $r) $r 'RP3RecoveryContinuation' $null;Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'RP-3 continuation ledger historical publication operation provenance is required'}
$results+=Invoke-Case 'C217' 'RP-6 RP-5 continuation accepts null historical provenance' {$r=New-Release;$l=Add-Rp6Metadata (New-ContinuationLedger $r) $r 'RP5EffectiveRelease' $null;$c=ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r;Assert-True ($null -eq $c.HistoricalPublicationOperationId) 'RP-5 historical provenance was synthesized';Assert-Eq 'Accepted' $c.RawMutationState 'state'}
$results+=Invoke-Case 'C218' 'RP-6 RP-5 continuation rejects fabricated historical provenance' {$r=New-Release;$l=Add-Rp6Metadata (New-ContinuationLedger $r) $r 'RP5EffectiveRelease' '00000000-0000-0000-0000-000000000001';Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'must not contain historical publication operation provenance'}
$results+=Invoke-Case 'C219' 'RP-6 selectionSource requires complete canonical release identity' {$r=New-Release;$l=New-ContinuationLedger $r;$l|Add-Member selectionSource 'RP5EffectiveRelease';$l.historicalPublicationOperationId=$null;Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} 'selectionSource requires complete canonical release identity'}
$results+=Invoke-Case 'C220' 'unsupported RP-6 selectionSource is rejected' {$r=New-Release;$l=Add-Rp6Metadata (New-ContinuationLedger $r) $r 'UnknownSource' $null;Assert-Throws {ConvertFrom-NuGetContinuationPublicationLedgerClaim $l $r} "selectionSource 'UnknownSource' is unsupported"}
$results|Format-Table -AutoSize
$failed=@($results|Where-Object Outcome -eq 'FAIL');if($failed.Count){$failed|ForEach-Object{Write-Host "$($_.Id) $($_.Name): $($_.Error)" -ForegroundColor Red};throw "RP-5C.2 continuation evidence claim conformance failed: $($failed.Count) case(s)."};Write-Host "RP-5C.2 continuation evidence claim conformance passed: $($results.Count)/$($results.Count)."
